/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.customComponents;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author wtf
 */
public class PanelActionNasabah extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelActionNasabah() {
        initComponents();
    }
    
    public void initEvent(TableActionEventNasabah ev, int row) {
        detailBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                ev.onDetail(row);
            }
        
        });
        
        refuseBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                ev.onRefuse(row);
            }
        
        });
    }

    public void setStatus(String status) {
        if ("Ditolak".equalsIgnoreCase(status) || "Lunas".equalsIgnoreCase(status) || "Disetujui".equalsIgnoreCase(status) || "Dibatalkan".equalsIgnoreCase(status)) {
            refuseBtn.setVisible(false);
        } else {
            refuseBtn.setVisible(true);
        }
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailBtn = new views.customComponents.ActionButton();
        refuseBtn = new views.customComponents.ActionButton();

        detailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/info.png"))); // NOI18N

        refuseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/cross.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refuseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refuseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.customComponents.ActionButton detailBtn;
    private views.customComponents.ActionButton refuseBtn;
    // End of variables declaration//GEN-END:variables
}
